version: '3.7'

services:
  docushare-auth-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - docushare-db
    environment:
      google_client_id: ${google_client_id}
      google_client_secret: ${google_client_secret}
      google_auth_server_host: localhost
      google_auth_server_port: 8080
      mysql_connection: jdbc:mysql://docushare-db:3306/docu_share_users
      mysql_username: user
      mysql_password: password
    networks:
      - docushare
  docushare-db:
    image: mysql:5.7
    ports:
      - "10097:3306"
    restart: always
    environment:
      MYSQL_DATABASE: docu_share_users
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - docushare-data:/var/lib/mysql
    networks:
      - docushare

volumes:
  docushare-data:

networks:
  docushare:

