version: '3.7'

services:
  docushare-auth-server:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    restart: always
    depends_on:
      - docushare-db
    env_file:
      - env.file
    environment:
      google_auth_server_host: localhost
      google_auth_server_port: 8080
      mysql_host: docushare-db
      mysql_port: 3306
      mysql_username: user
      mysql_password: password
    networks:
      - docushare
  docushare-db:
    container_name: docushare-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: docu_share_users
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - docushare-data:/var/lib/mysql
    networks:
      - docushare

volumes:
  docushare-data:

networks:
  docushare:

