server:
  port: ${service_port}
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${google_client_id}
            clientSecret: ${google_client_secret}
            redirect-uri: ${google_redirect_url}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql_host}:${mysql_port}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
jwt:
  privateKey:
    location: keys/private_key.der
  publicKey:
    location: keys/public_key.der