spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${google_client_id}
            clientSecret: ${google_client_secret}
            redirect-uri: http://localhost:8080/oauth/google
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql_host}:${mysql_port}/${mysql_db}
    username: ${mysql_username}
    password: ${mysql_password}
jwt:
  privateKey:
    location: keys/private_key.der
  publicKey:
    location: keys/public_key.der